civi_ext_manager:
    resource: "@CiviExtManagerBundle/Controller/"
    type:     annotation
    prefix:   /extdir/

civi_upgrade_manager_upgrade_report:
    resource: "@CiviDistManagerBundle/Controller/UpgradeReportController.php"
    type:     annotation

civi_upgrade_manager:
    resource: "@CiviDistManagerBundle/Resources/config/routing.yml"
    #type:     annotation
    prefix:   /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
