services:
  civi_ext_manager.cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: ['%kernel.cache_dir%/extdir']

  civi_ext_manager.repo:
    class: CiviExtManagerBundle\CiviExtRepository
    arguments: ['@civi_ext_manager.cache']
