services:
  civi_ext_manager.cache:
    class: 'Doctrine\Common\Cache\FilesystemCache'
    arguments: ['%kernel.cache_dir%/extdir']

  civi_ext_manager.repo:
    class: CiviExtManagerBundle\ExtRepository
    arguments: ['@civi_ext_manager.cache', '@event_dispatcher']

  civi_ext_manager.url_source:
    class: 'CiviExtManagerBundle\ExtUrlSource'
    arguments: ['https://civicrm.org/extdir/{filterExpr}/single']
    tags:
     -
       name: 'kernel.event_subscriber'

  civi_ext_manager.mock_source:
    class: 'CiviExtManagerBundle\ExtMockSource'
    tags:
     -
       name: 'kernel.event_subscriber'

  civi_ext_manager.backfill_categories:
    class: 'CiviExtManagerBundle\ExtBackfillCategories'
    arguments: ['%kernel.root_dir%/config/ext-categories.json', '@logger']
    tags:
     -
       name: 'kernel.event_subscriber'